version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_secret
      POSTGRES_DB: financial
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - template01.network

  backend:
    build:
      context: ./backend
    command: bash -c "./prestart.sh"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=financial
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_secret
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ENV=dev
    depends_on:
      - db
    networks:
      - template01.network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend


volumes:
  postgres_data:
    driver: local

networks:
  template01.network:
    driver: bridge
